version: '2.1'

services:
    postgis-service:
      image: bde2020/pilot-sc4-postgis:v0.1.0       
      container_name: postgres
      restart: unless-stopped
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD="password"
      networks:
        - pilot-sc4-net
        
    map-match-service:
     image: bde2020/pilot-sc4-rserve:v0.1.0
     container_name: map-match
     restart: unless-stopped
     ports:
       - "6311:6311"
     environment:
        - POSTGRES_PASSWORD="password"
     depends_on:
       - postgis-service
     networks:
       - pilot-sc4-net
    

networks:
    pilot-sc4-net:
        external: true
